[project]
name = "src"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Mauricio da Paixão Costa", email = "mauriciopaixao21@gmail.com"},
]
dependencies = ["fastapi>=0.135.1", "uvicorn>=0.41.0", "python-dotenv>=1.2.2", "ruff>=0.15.5", "pydantic-settings>=2.13.1", "sqlalchemy>=2.0.48", "psycopg2-binary>=2.9.11", "alembic>=1.18.4", "loguru>=0.7.3", "sentry-sdk[fastapi]>=2.54.0"]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.ruff]
line-length = 88
target-version = "py312"
select = ["E", "F", "I", "N", "W", "B", "C4"]
ignore = ["E501"] # Ignorar linha muito longa se necessário

[tool.ruff.isort]
known-first-party = ["src"]
